back_right_shoulder: 0
back_left_shoulder: 1
front_right_shoulder: 2
front_left_shoulder: 3
back_right_hip: 4
back_left_hip: 5
front_right_hip: 6
front_left_hip: 7
back_right_knee: 8
back_left_knee: 9
front_right_knee: 10
front_left_knee: 11
