back_left_hip:
  max: 180
  mid: 90
  min: 0
back_left_knee:
  max: 180
  mid: 90
  min: 0
back_left_shoulder:
  max: 180
  mid: 90
  min: 0
back_right_hip:
  max: 180
  mid: 90
  min: 0
back_right_knee:
  max: 180
  mid: 90
  min: 0
back_right_shoulder:
  max: 180
  mid: 90
  min: 0
front_left_hip:
  max: 180
  mid: 90
  min: 0
front_left_knee:
  max: 180
  mid: 90
  min: 0
front_left_shoulder:
  max: 180
  mid: 90
  min: 0
front_right_hip:
  max: 180
  mid: 90
  min: 0
front_right_knee:
  max: 180
  mid: 90
  min: 0
front_right_shoulder:
  max: 180
  mid: 90
  min: 0
